  # Where is it? Leave blank or commented out to use default
  path: /Users/j.mccleary/Research/dusty_halos/catalogs/prep_cat_output
  #path: /work/mccleary_group/dusty_halos/catalogs/prep_cat_output
  filename: 'DoubleMasked_GSWLC-X2_in_SDSS_z_lt_0.2.fits'
  # nickname for table if we are matching to another catalog
  tabname: 'GSWLC_gals'
  ### WCS frame ###
  coordframe: 'icrs'
  ### RA/Dec units ###
  coord_units: 'deg'
  ### RA/Dec column names ###
  ra_key: 'RA'
  ### Dec column name ###
  dec_key: 'Dec'
  ### Redshift column name ###
  z_key: 'z'
