  # Where is it? Leave blank or commented out to use default
  #path: /work/mccleary_group/dusty_halos/catalogs/prep_cat_output
  path: '/Users/j.mccleary/Research/dusty_halos/catalogs/prep_cat_output'
  # Name of file
  filename: redmagic_hiz_y3_GOLD_JOINED_catalog.fits
  # nickname for table if we are matching to another catalog
  tabname: 'redmagic_hiz_y3gold_joined'
  # WCS frame
  coordframe: 'icrs'
  # RA/Dec units
  coord_units: 'deg'
  # RA/Dec column names
  ra_key: 'ra_redmagic_hiz'
  # Dec column name
  dec_key: 'dec_redmagic_hiz'
  # Redshift column name
  z_key: 'zredmagic'
  # optional for redmagic only, basically
  z_bin_number: 'bin_number'
