  ### Where is it? Leave blank or commented out to use default ###
  path: /Users/j.mccleary/Research/dusty_halos/catalogs/prep_cat_output
  #path: /work/mccleary_group/dusty_halos/catalogs/prep_cat_output
  filename: 'DoubleMasked_WISExSCOS_randoms3.fits'
  # nickname for table if we are matching to another catalog
  tabname: 'WISExSCOS_randoms'
  # WCS frame
  coordframe: 'icrs'
  # RA/Dec units
  coord_units: 'deg'
  # RA/Dec column names
  ra_key: 'ra'
  # Dec column name
  dec_key: 'dec'
  # Redshift column name
  z_key: 'z'
  # optional for redmagic only, basically
  # z_bin_number: 'bin_number'
