################################################################################
#             CONFIGURATION FILE: dust_calc_runner.py                          #
################################################################################
# -----------------
# Input catalogs
# -----------------

# cat_config: path to configuration file specifying catalog properties
# NOTES:
#  - allowed keys for "redshifts" are: use_bin_numbers, nbins, and min_z
#  - "treecorr_npatch" sets the number of sky patches used in treecorr

background_catalog:
  cat_config: 'configs/catalog_configs/sdss_colorcut_galaxies.yaml'
  treecorr_npatch: 10   # Set number of treecorr patches
  redshifts: # How to deal with redshifts
    nbins: 4

background_randoms:
  cat_config: 'configs/catalog_configs/sdss_colorcut_randoms.yaml'
  redshifts: # How to deal with redshifts
    nbins: 4

foreground_catalog:
  cat_config: 'configs/catalog_configs/WISExSCOS_sdss.yaml'

foreground_randoms:
  cat_config: 'configs/catalog_configs/WISExSCOS_sdss_randoms.yaml'

# ------------------
# Output parameters
# ------------------

# Where output files and plots will get saved
output_path: 'output/sdss_csfd'
# basename or prefix for assorted files to save
output_basename: 'dustcorrel_csfd_4zbins'
# Plot output dust profile in kiloparsecs (False) or arcminutes (True)
use_kpc: True

# -----------------
# Correlation function parameters:
# -----------------
treecorr_params:
  min_sep: 0.1
  max_sep: 220.0
  bin_size: 0.6
  sep_units: 'arcmin'
  var_method: 'sample'

# Parameters for dust model
dust_params:
  # Model must be one of the models specified in dust_extinction.averages or 
  # dust_extinction.parameter_averages (Note: these are cASe SeNsItIvE)
  model: 'G24_SMCAvg'
  # Ratio of selective to total extinction (if required by dust model)
  R: 3.1
  # Extinction in V band (if required by dust model)
  A_V: 1
  # Bandpass column names in catalog
  band_names: ['u_corr_csfd', 'g_corr_csfd', 'r_corr_csfd', 'i_corr_csfd', 'z_corr_csfd']
  #  Error/uncertainty column names in catalog (in order, please!)
  err_names: ['err_u', 'err_g', 'err_r', 'err_i', 'err_z']
  # Central wavelengths (spectrum) to model; should match number of bands!
  wavelengths: [3586.8, 4716.7, 6165.1, 7475.9, 8922.9]
