################################################################################
#                            CONFIGURATION FILE                               #
################################################################################

# Description:
# This configuration file allows you to customize the settings for
# prep_random_cat_runner.py

# Note:
# - Do not change the variable names (the text before the equal sign).
# - Only modify the values on the right side of the colon sign (:).

# General Settings:
# -----------------
# catalog_path: generic location for catalogs
# output_path: where to save files

# Set some defaults
paths:
  # general path for catalogs
  catalog_path: '/work/mccleary_group/dusty_halos/catalogs/'
  # Where to save outputs
  output_path: '/work/mccleary_group/dusty_halos/catalogs/prep_cat_gwslc'

# How many random points are we making?
# Suggestion: use 1e6 for making overlap plots, > 3e7 for science
nrand: 5e8

# Output name for random catalog; note that "masked_" will be added as prefix
output_name: 'sdss_bg_photoz_randoms.fits'

# Populate if comparison to another catalog's RA, Dec distribution is desired
#comparison_cat: '/work/mccleary_group/dusty_halos/catalogs/prep_cat_sdss/DoubleMasked_sdss_bg_photoz.fits'

# HpMask for which random points are desired
mask1:
  # Where is mask2? Leave blank or commented out to use default paths
  path:
  # What is it called?
  filename: 'sdss_bg_photoz_healpix_mask.fits'
  # IMPORTANT!!! GET COORDINATE FRAME CORRECT OR MASKING WILL FAIL!
  coordframe: 'icrs'
  # Is mask partial?
  partial: False
