################################################################################
#                            CONFIGURATION FILE                               #
################################################################################

# Description:
# This configuration file allows you to customize the settings for
# cat_prep_runner.py

# General Settings:
# -----------------
paths:
  # general path for catalogs
  # catalog_path: '/Users/j.mccleary/Research/dusty_halos/catalogs'
  catalog_path: '/work/mccleary_group/dusty_halos/catalogs'
  # Where to save outputs
  output_path: '/work/mccleary_group/dusty_halos/catalogs/prep_cat_sdss'

#
# Input catalogs and masks:
# -----------------

# This is probably the background catalog
background_catalog:
  # Where is it? Leave blank or commented out to use default
  path:
  # Name of catalog
  filename: 'sdss_bg_photoz.fits'
  # nickname for table if we are matching to another catalog
  tabname: 'sdss_bg'
  # WCS frame
  coordframe: 'icrs'
  # RA/Dec units
  coord_units: 'deg'
  # RA/Dec column names
  ra_key: 'ra'
  dec_key: 'dec'
  # Name for filtered (possibly joined) output catalog
  output_name:
  # Are we matching? Uncomment fields below if true!

# background mask
background_mask:
  # Where is it? Leave blank or commented out to use default paths
  path:
  # What is it called?
  filename: 'sdss_bg_photoz_healpix_mask.fits'
  # IMPORTANT!!! GET COORDINATE FRAME CORRECT OR MASKING WILL FAIL!
  coordframe: 'icrs'
  # Is mask partial?
  partial: False

# This is probably the foreground
foreground_catalog:
  # Where is it?
  #path:
  # What is it called ?
  filename: 'wiseScosPhotoz160708_zlt0.2_bCal_lt_16.fits'
  # RA, Dec names + units + coordframe
  coordframe: 'galactic'
  ra_key: 'l'
  dec_key: 'b'
  coord_units: 'deg'


# probably foreground mask
foreground_mask:
  # Where is it?
  path:
  # What is it called?
  filename: 'WISExSCOSmask.fits'
  # IMPORTANT!!! GET COORDINATE FRAME CORRECT OR MASKING WILL FAIL!
  coordframe: 'galactic'
  # Is mask partial? When in doubt, do not pass this argument. Code will figure it out
