################################################################################
#                            CONFIGURATION FILE                               #
################################################################################

# Description:
# This configuration file allows you to customize the settings for
# prep_fg_randoms_runner.py

# Note:
# - Do not change the variable names (the text before the equal sign).
# - Only modify the values on the right side of the equal sign (=).

# General Settings:
# -----------------
# catalog_path: generic location for catalogs
# output_path: where to save files

# Set some defaults
paths:
  # general path for catalogs
  catalog_path: '/Users/j.mccleary/Research/dusty_halos/catalogs'
  #catalog_path: '/work/mccleary_group/dusty_halos/catalogs'
  # Where to save outputs
  #output_path: '/work/mccleary_group/dusty_halos/catalogs/prep_cat_output'
  output_path: '/Users/j.mccleary/Research/dusty_halos/catalogs/prep_cat_gwslc'

# How many random points are we making?
# Suggestion: use 1e6 for making overlap plots, > 3e7 for science
nrand: 1e6

# Output name for random catalog; note that "masked_" will be added as prefix
output_name: 'gwslc_randoms_testing.fits'

# If you want to compare (plot) RA/Dec distributions of two catalogs
comparison_cat:

# main catalog mask
mask1:
  # Where is it? Leave blank or commented out to use default paths
  #path: '/Users/j.mccleary/Research/dusty_halos/catalogs/prep_cat_gwslc/'
  # What is it called?
  filename: 'GSWLC-X2_in_SDSS_z_lt_0.2_healpix_mask.fits'
  # IMPORTANT!!! GET COORDINATE FRAME CORRECT OR MASKING WILL FAIL!
  coordframe: 'icrs'
  # Is mask partial?
  partial: False

# additional mask -- optional
#mask2:
#  # Where is it? If blank, assumes general catalog_path
#  path:
#  # What is it called?
#  filename: 'y3_gold_2.2.1_RING_joint_redmagic_v0.5.1_wide_maglim_v2.2_mask.fits'
#  # IMPORTANT!!! GET COORDINATE FRAME CORRECT OR MASKING WILL FAIL!
#  coordframe: 'icrs'
#  # Is mask partial? When in doubt, do not pass this argument; code will figure it out.
#  partial: True
