################################################################################
#                            CONFIGURATION FILE                               #
################################################################################

# Description:
# This configuration file allows you to customize the settings for
# cat_prep_runner.py

# General Settings:
# -----------------
paths:
  # general path for catalogs
  catalog_path: '/work/mccleary_group/dusty_halos/catalogs'
  # Where to save outputs
  output_path: '/work/mccleary_group/dusty_halos/catalogs/prep_cat_output'

#
# Input catalogs and masks:
# -----------------

# This is probably the background catalog
background_catalog:
  # Where is it? Leave blank or commented out to use default
  path:
  filename: 'y3a2_gold2.2.1_redmagic_highlum_highz.fits'
  # nickname for table if we are matching to another catalog
  tabname: 'redmagic_hiz'
  # WCS frame
  coordframe: 'icrs'
  # RA/Dec units
  coord_units: 'deg'
  # RA/Dec column names
  ra_tag: 'ra'
  dec_tag: 'dec'
  # Name for filtered (possibly joined) output catalog
  output_name: 
  # Are we matching? Uncomment fields below if true!
  match:
    # Set the path to catalog to be matched
    path: '/work/mccleary_group/dusty_halos/catalogs'
    # Name of catalog file
    filename: 'des_y3_gold_MOF_highpurity_gals.fits'
    # Should be 'kw', 'coordinates', or 'random'
    match_type: 'kw'
    # If kw matching, specify
    match_kw: 'coadd_object_id'
    # nickname for table
    tabname: 'y3_GOLD'

# background mask
background_mask:
  # Where is it? Leave blank or commented out to use default paths
  path:
  # What is it called?
  filename: 'y3_gold_2.2.1_RING_joint_redmagic_v0.5.1_wide_maglim_v2.2_mask.fits'
  # IMPORTANT!!! GET COORDINATE FRAME CORRECT OR MASKING WILL FAIL!
  coordframe: 'icrs'
  # Is mask partial?
  partial: True

# This is probably the foreground
foreground_catalog:
  # Where is it?
  #path:
  # What is it called ?
  filename: 'wiseScosPhotoz160708_z_lt_0.2.fits'
  # Name for filtered (possibly joined) output catalog
  output_name: 
  # RA, Dec names + units + coordframe
  coordframe: 'galactic'
  ra_tag: 'l'
  dec_tag: 'b'
  coord_units: 'deg'
  # output_path: '/Users/j.mccleary/Research/dusty_halos/catalogs'
  # Are we matching? Uncomment if matching
  match:

# probably foreground mask
foreground_mask:
  # Where is it?
  path:
  # What is it called?
  filename: 'WISExSCOSmask.fits'
  # IMPORTANT!!! GET COORDINATE FRAME CORRECT OR MASKING WILL FAIL!
  coordframe: 'galactic'
  # Is mask partial? When in doubt, do not pass this argument. Code will figure it out
