################################################################################
#                            CONFIGURATION FILE                               #
################################################################################

# Description:
# This configuration file allows you to customize the settings for
# cat_prep_runner.py

# Note:
# - Do not change the variable names (the text before the equal sign).
# - Only modify the values on the right side of the equal sign (=).

# General Settings:
# -----------------
# catalog_path: generic location for catalogs
# output_path: where to save files

# Set some defaults because I am lazy
paths:
  # general path for catalogs
  catalog_path: '/work/mccleary_group/dusty_halos/catalogs'
  #catalog_path: '/Users/j.mccleary/Research/dusty_halos/catalogs'
  # Where to save outputs
  output_path: '/work/mccleary_group/dusty_halos/catalogs/prep_cat_output'
  #output_path: '/Users/j.mccleary/Research/dusty_halos/catalogs/prep_cat_output'
#
#
# Input catalogs and masks:
# -----------------

# This is probably the background
background_catalog:
  # Where is it? Leave blank or commented out to use default
  #path:
  filename: 'y3a2_gold2.2.1_redmagic_highdens_randoms.fits'
  # table nickname for naming outputs and duplicate columns (if joining)
  tabname: 'redmagic_hidens_randoms'
  # WCS frame
  coordframe: 'icrs'
  # RA/Dec units
  coord_units: 'deg'
  # Azimuth-type column name
  ra_key: 'ra'
  # Altitude-type column name
  dec_key: 'dec'
  # Are we matching? Uncomment fields below if true!
  match:
    # Set the path to catalog to be matched
    path: '/work/mccleary_group/dusty_halos/catalogs/prep_cat_output'
    #catalog_path: '/Users/j.mccleary/Research/dusty_halos/catalogs'
    # Name of catalog file
    filename: 'redmagic_hidens_y3_GOLD_JOINED_catalog.fits'
    # Should be 'kw', 'coordinates', or 'random'
    match_type: 'random'
    # If type is random: z1 is the catalog to be augmented -- leave it blank to make a redshift column!!!
    z1_colname: 'z'
    # If type is random: z2 is matching photometry catalog
    z2_colname: 'zredmagic'
    # nickname for table, used to name outputs
    tabname: 'y3_GOLD'

# background mask
background_mask:
  # What is it called?
  filename: 'y3_gold_2.2.1_RING_joint_redmagic_v0.5.1_wide_maglim_v2.2_mask.fits'
  # IMPORTANT!!! GET COORDINATE FRAME CORRECT OR MASKING WILL FAIL!
  coordframe: 'icrs'
  # Is mask partial?
  partial: True

# This is probably the foreground
foreground_catalog:
  # What is it called ?
  filename: 'WISExSCOS_randoms4.fits'
  # RA, Dec names + units + coordframe
  coordframe: 'icrs'
  ra_key: 'ra'
  dec_key: 'dec'
  coord_units: 'deg'
  # Are we matching? Uncomment if matching
  match:

# probably foreground mask
foreground_mask:
  # What is it called?
  filename: 'WISExSCOSmask.fits'
  # IMPORTANT!!! GET COORDINATE FRAME CORRECT OR MASKING WILL FAIL!
  coordframe: 'galactic'
