################################################################################
#                            CONFIGURATION FILE                               #
################################################################################

# Description:
# This configuration file allows you to customize the settings for
# cat_prep_runner.py

# General Settings:
# -----------------
paths:
  # general path for catalogs
  catalog_path: '/Users/j.mccleary/Research/dusty_halos/catalogs'
  # Where to save outputs
  output_path: '/Users/j.mccleary/Research/dusty_halos/catalogs/prep_cat_output'

#
# Input catalogs and masks:
# -----------------

# This is probably the background catalog
background_catalog:
  # Where is it? Leave blank or commented out to use default
  path:
  # Name of catalog
  filename: 'y3a2_gold2.2.1_redmagic_highdens.fits'
  # nickname for table if we are matching to another catalog
  tabname: 'redmagic_hidens'
  # WCS frame
  coordframe: 'icrs'
  # RA/Dec units
  coord_units: 'deg'
  # RA column names
  ra_key: 'ra'
  # Dec column name
  dec_key: 'dec'
  # Are we matching? Uncomment fields below if true!
  match:
    # Set the path to catalog to be matched
    path: '/Users/j.mccleary/Research/dusty_halos/catalogs/'
    # Name of catalog file
    filename: 'redmagic_hidens_y3_GOLD_JOINED_catalog.fits'
    # Should be 'kw', 'coordinates', or 'random'
    match_type: 'kw'
    # If kw matching, specify
    match_kw: 'coadd_object_id'
    # nickname for table
    tabname: 'y3_GOLD'

# background mask
background_mask:
  # What is it called?
  filename: 'y3_gold_2.2.1_RING_joint_redmagic_v0.5.1_wide_maglim_v2.2_mask.fits'
  # IMPORTANT!!! GET COORDINATE FRAME CORRECT OR MASKING WILL FAIL!
  coordframe: 'icrs'
  # Is mask partial?
  partial: True

# This is probably the foreground
foreground_catalog:
  # What is it called ?
  filename: 'wiseScosPhotoz160708_redshift_cut.fits'
  # WCS coordinate frame
  coordframe: 'galactic'
  # azimuth-type keyword (could be l)
  ra_key: 'l'
  # altitude-type keyword
  dec_key: 'b'
  # WCS coordinate units (usually deg)
  coord_units: 'deg'


# probably foreground mask
foreground_mask:
  # What is it called?
  filename: 'WISExSCOSmask.fits'
  # IMPORTANT!!! GET COORDINATE FRAME CORRECT OR MASKING WILL FAIL!
  coordframe: 'icrs'
  # Is mask partial? When in doubt, do not pass this argument. Code will figure it out
